### ISSUE TITLE
Use privatebin-cli in nodejs script

### ISSUE THREAD

**Issue by rylebrun** [pixelfactoryio/privatebin-cli#23]
Hi, 
First at all, thanks for your work and the latest fixes. 
Do you have some snippets or tips to use privatebin-cli in an existing nodejs script (so, not really the CLI tool but like an import in a script).
I need to parse a file to batch post hundred of link by mail, I've try with the `child_process / exec` method but it's dirty to read stdout. I'll prefer save the native result as an object to process loop operations on an array all all my results.
Thanks in advance,

**Comment by amine7536** [comment]
Hi, you can import it directly in your script like this :

```javascript
const bs58 = require("bs58");
const crypto = require("crypto");
const privatebin = require("@pixelfactory/privatebin");

const client = new privatebin.Privatebin({
  baseURL: "https://privatebin.net",
  headers: {
    common: {
      "Content-Type": "application/json",
      "X-Requested-With": "JSONHttpRequest",
    },
  },
});

randomKey = crypto.randomBytes(32);

(async () => {
  // Encrypt
  const encryptedPaste = await client.encryptPaste(
    "Hello World", // Message
    randomKey,
    {
      url: "https://privatebin.net",
      expire: "5min",
      burnafterreading: 0,
      opendiscussion: 0,
      output: "text",
      compression: "zlib",
    }
  );
  console.log(encryptedPaste);
  console.log(`pasteURL=https://privatebin.net${encryptedPaste.url}#${bs58.encode(randomKey)}`);

  // Decrypt
  const decryptedPaste = await client.decryptPaste(
    encryptedPaste.id,
    randomKey
  );
  console.log(decryptedPaste);
})();
```

- Response from privatebin.net :
```
{
  status: 0,
  id: 'e68ed347d09f4964',
  url: '/?e68ed347d09f4964',
  deletetoken: '2a8627ca0ebb7be1b9d5ab96efde04ad0ffeafabb0db47710373fd2fb63cd130'
}
```

- URL : you will need to "craft" it,  the `randomKey` it's never sent to the server.
```
pasteURL=https://privatebin.net/?e68ed347d09f4964#Gx4z9gZfbabj7y8FeqzeqGXAiLVWX3EaV3Pg6Pstkckd
```

I hope this helps. I will try to add this to the README when I get time.

**Comment by rylebrun** [comment]
Thanks @amine7536 🙏, you make my day.

**Comment by amine7536** [comment]
Hi, since version 2.0.0 there are some breaking changes :

- `privatebin.Privatebin` has been renamed to `PrivatebinClient`
- you don't need to pass an `AxiosRequestConfig` at the client initialization, only the baseUrl `const privatebin = new PrivatebinClient('https://myprivatebin.net');` 

I added working example in the README. https://github.com/pixelfactoryio/privatebin-cli#library
I'm closing this issue, but feel free to reopen it if you need more information.
