### ISSUE TITLE
TextEncoding error

### ISSUE THREAD

**Issue by alexanderrtaylor** [pixelfactoryio/privatebin-cli#49]
Environment:
@pixelfactory/privatebin@2.6.0
One linux machine running Amazon Linux 2 - not working
One Mac machine running BigSur - working

I have been having an issue with a recent linux machine I installed this module onto that I was hoping was just a setup error as it worked fine on a Mac machine but when I run the `send` command I get `ERROR: TextEncoder is not defined`

Command looks like this:

```
privatebin send -u $PASTEBIN_SITE -e 1week -o json '$PASSWORD'
```

And on the Mac machine this works normally but not on the Linux machine. Everything I am reading on the internet is that it is related to a TextEncoder package which needs to be imported into this privatebin-cli module but I am not certain

Is this just a setup error or is the commit from 4 months ago causing this: https://github.com/pixelfactoryio/privatebin-cli/commit/185e8cc8870f88bb6b2682aa3ac953d28d328e5e since prior would not have that Encoding

**Comment by amine7536** [comment]
Hi, @alexanderrtaylor, what's the version of NodeJS you are using on the Amazon Linux machine ?

**Comment by alexanderrtaylor** [comment]
@amine7536 v14.16.0 sorry for the late response (I didnt get the email for some reason of a comment)

Maybe it is a failure with my install of NodeJS?

**Comment by amine7536** [comment]
Hi @alexanderrtaylor, I've done some test and I get the error `ERROR: TextEncoder is not defined` when I use Node versions below `v11.15.0`. 
In the `privatebin` script I'm adding the shebang `#!/usr/bin/env node`, could it be possible that you have more than one NodeJS installed ?

**Comment by alexanderrtaylor** [comment]
@amine7536 I dont think that would be possible as we installed NodeJS on a fresh AWS instance where it was previously not installed or at least it is not on any path I am aware of and is not anywhere I can see in the bin folders. But I can double check in case.
