### ISSUE TITLE
pasteURL contains extra directory in the path

### ISSUE THREAD

**Issue by yogeshpowar** [pixelfactoryio/privatebin-cli#63]
```
$privatebin -V
2.6.1
```

`$echo test | privatebin send -u https://some.domain.com/projdir`

```
pasteId: 4f966295ea4b7c00
pasteURL: https://some.domain.com/projdir/projdir/?4f966295ea4b7c00#248b31ayMLf5iN5wje6XKQMs3VmerqNv7wgjgdc3DLjn
deleteURL: https://some.domain.com/projdir/?pasteid=4f966295ea4b7c00&deletetoken=83e4616abcca578b8e8464cc2e280099b4a9a5c428a7e5d7adb1ccc03d5e3796
```

Notice above that `projdir` is added twice in the `pasteURL`
BTW `deleteURL` is right.

**Comment by amine7536** [comment]
I was able to reproduce the issue but didn't find to time implement the fix. I will try to work on this issue in the coming days hopefully.
