### ISSUE TITLE
{ status: 1, message: 'Invalid data.' }

### ISSUE THREAD

**Issue by maggie0002** [pixelfactoryio/privatebin-cli#72]
Adapting the code from the README, expect it only ever returns:

`{ status: 1, message: 'Invalid data.' }`.

Not really sure what to make of the error, I can't find the error message anywhere in the code. 

```
import { PrivatebinClient } from "@pixelfactory/privatebin";

const crypto = await import("crypto");

const privatebin = new PrivatebinClient();
privatebin.baseURL = "https://localhost:8080";

const key = crypto.webcrypto.getRandomValues(new Uint8Array(32));
const msg = "Hello World!";

const opts = {
  expire: "5min",
  burnafterreading: 0,
  opendiscussion: 0,
  output: "text",
  compression: "zlib",
};

let paste;
try {
  paste = await privatebin.sendText(msg, key, opts);
} catch (err) {
  console.error(err);
}
console.log(paste);
```

**Comment by maggie0002** [comment]
Typically, the next thing I look at after posting seems to be the issue. `opts` requires a `  textformat: "plaintext",` string.

Although now it is sending, it doesn't return a URL to access the submitted content.

**Comment by raulfb** [comment]
I have the same problem.
It returns:
`{
  status: 0,
  id: 'af4e7eaee82229dd',
  url: '/?af4e7eaee82229dd',
  deletetoken: '1111a7331755553dc3ec1381305f07d610def2ff4ad9d95557555f6f47a4261d7851f'
}`

**Comment by raulfb** [comment]
If I set "opts" as:

`
    const opts = {
    expire: '1week',
    burnafterreading: 1,
    opendiscussion: 0,
    compression: 'none',
    output: 'json'
}`

It gives me the same error that you mentioned:

`
{ status: 1, message: 'Invalid data.' }
`

But if I set "opts" as:

`  const opts = {
    textformat: 'plaintext',
    expire: '1week',
    burnafterreading: 1,
    opendiscussion: 0,
    compression: 'none',
    output: 'json'
}`

It gives me:

`{
  status: 0,
  id: '32ba5177c5f77d1a',
  url: '/?32ba5177c5f77d1a',
  deletetoken: '28a72eeac534f47604f51ee9e86ee7f96d1caa8c552791d2976e56b6ab25dbf5'
}`


But I can generate the url to access the submitted content.

**Comment by raulfb** [comment]
I managed to get it to return the URL to access the submitted content.
I also added the `textformat` to `opts` to fix the problem.
I create the pull request. 
Thanks
